# Generated by Django 3.0.5 on 2020-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_birth',
            field=models.DateTimeField(null=True, verbose_name='date birth'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(default='Female', max_length=10, verbose_name='gender'),
        ),
    ]
