# Generated by Django 3.0.5 on 2020-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200430_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_birth',
            field=models.DateField(null=True, verbose_name='date birth'),
        ),
    ]
