# Generated by Django 3.0.5 on 2020-05-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200430_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_temp',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email_temp_hash',
            field=models.CharField(default='', max_length=200),
        ),
    ]
