# Generated by Django 3.0.5 on 2020-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200504_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_temp',
            field=models.EmailField(default=False, max_length=100, null=True, verbose_name='email_temp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email_temp_hash',
            field=models.CharField(default='', max_length=200, verbose_name='email_temp_hash'),
        ),
    ]
