# Generated by Django 3.0.5 on 2020-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default='', max_length=200, verbose_name='token'),
        ),
    ]
