# Generated by Django 3.0.5 on 2020-06-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
