# Generated by Django 3.0.5 on 2020-05-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=300)),
                ('yield_total', models.CharField(max_length=50)),
                ('calories_total', models.CharField(max_length=50)),
                ('weight_total', models.CharField(max_length=50)),
                ('healthLabels', models.CharField(max_length=300)),
                ('cautions', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_description', models.TextField(blank=True)),
                ('how_many_person', models.IntegerField()),
                ('added_date', models.DateTimeField()),
                ('recipe_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.Category')),
                ('recipe_cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.Cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(max_length=200)),
                ('entry_type', models.CharField(choices=[('totalNutrients', 'totalNutrients'), ('totalDaily', 'totalDaily'), ('totalNutrientsKCal', 'totalNutrientsKCal')], default='totalNutrients', max_length=50, verbose_name='entry_type')),
                ('nutrient_label', models.CharField(max_length=200)),
                ('nutrient_quantity', models.FloatField(default=0.0)),
                ('nutrient_unit', models.CharField(max_length=300)),
                ('ingredient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.Ingredient')),
                ('recipe_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.Recipe'),
        ),
    ]
