# Generated by Django 3.0.5 on 2020-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200506_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cautions',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='healthLabels',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='weight_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_total',
            field=models.CharField(default='', max_length=100),
        ),
    ]
