# Generated by Django 3.0.5 on 2020-05-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200506_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrients',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='nutrient_label',
        ),
    ]
