# Generated by Django 3.0.5 on 2020-06-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recipe_recipe_food_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories_total',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cautions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='healthLabels',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='weight_total',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yield_total',
        ),
    ]
