# Generated by Django 3.0.5 on 2020-06-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_menus_menu_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Nutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(max_length=200)),
                ('nutrient_unit', models.CharField(max_length=300)),
                ('needed', models.FloatField(default=0.0)),
            ],
        ),
    ]
