# Generated by Django 3.0.5 on 2020-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_daily_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_nutrients',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='daily_nutrients',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10, verbose_name='gender'),
        ),
    ]
