# Generated by Django 3.0.5 on 2020-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproviders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproviders',
            name='provider_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodproviders',
            name='provider_long',
            field=models.FloatField(default=0.0),
        ),
    ]
