# Generated by Django 3.0.5 on 2020-06-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodproviders', '0002_auto_20200615_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodproviders',
            old_name='recipe_description',
            new_name='provider_description',
        ),
    ]
