# Generated by Django 3.0.5 on 2020-06-15 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodproviders', '0003_auto_20200615_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerProvider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targetProvider', to=settings.AUTH_USER_MODEL)),
                ('targetProvider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followerProvider', to='foodproviders.FoodProviders')),
            ],
        ),
    ]
